version: "3"

tasks:
  install-lammps:
    desc: "Automates LAMMPS installation across different Operating Systems (Windows, Mac, Linux)."
    cmds:
      - python scripts/install_lammps.py

  run:
    desc: "Run a LAMMPS simulation with a specified number of cores. Usage: task run -- <file.lammps> <cores>"
    vars:
      DIR: '{{index (.CLI_ARGS | splitList " ") 0 | dir}}'
      FILE: '{{index (.CLI_ARGS | splitList " ") 0 | base}}'
      CORES: '{{index (.CLI_ARGS | splitList " ") 1}}'
    cmds:
      - cd {{.DIR}} && mpirun -np {{.CORES}} lmp_mpi -in {{.FILE}}

  run-4:
    desc: "Run a LAMMPS simulation with 4 cores. Usage: task run-4 -- <file.lammps>"
    vars:
      DIR: '{{.CLI_ARGS | dir}}'
      FILE: '{{.CLI_ARGS | base}}'
    cmds:
      - cd {{.DIR}} && mpirun -np 4 lmp_mpi -in {{.FILE}}

  run-8:
    desc: "Run a LAMMPS simulation with 8 cores. Usage: task run-8 -- <file.lammps>"
    vars:
      DIR: '{{.CLI_ARGS | dir}}'
      FILE: '{{.CLI_ARGS | base}}'
    cmds:
      - cd {{.DIR}} && mpirun -np 8 lmp_mpi -in {{.FILE}}

  prod:
    desc: "Run the final 20-PFAS upper interface simulation. Usage: task prod -- <cores>"
    vars:
      DIR: 'src/pfas/multi_pfas/lammps'
      FILE: '20pfas_upper.lammps'
      CORES: '{{.CLI_ARGS}}'
    cmds:
      - cd {{.DIR}} && mpirun -np {{.CORES}} lmp_mpi -in {{.FILE}}
